org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
loader_version=0.17.2
loom_version=1.11.1
fabric_api_version=0.116.5+1.21.1

mod_version=0.3.0-alpha.1
maven_group=dev.steppedplayeranimations
archives_base_name=stepped-player-animations
